sudo: false
language: ruby
rvm:
  - 2.4.3

script:
  - bundle exec rspec

deploy:
  provider: rubygems
  api_key:
    secure: NLkVCnre4dZ/AhtJlKyY51Ux9XzA8U4Nx4AJ/mVQp/tfU45XHxY1L+a2+7j5NcpdD9bklaouXPWsQIjWg4ZV28C1pQZH+szji9+C/qweatUch2aeTDhbLzhG1IQE23sOaHPrCrDK32I5IKW+b7kYQzkbHp7KxFm9Uhm5bljDHIUrS38YRIr3RMaIv7UGrmVf8Ff5eC9+nigzQ3aw2Vq9EAzkpJdFKa1dA1ws4SCUNwh6P5KVICgALIioPljV/07BY/wolBQ4PDPyHy5JIKBtBZ3awnOUGNsXHSKBvMO7u4V7Vy4QTHzv4FayKx7v/HBU8Z9HUf5ErCZpYR0q3pKMiDkkvRt7eqr/U/9vQJI+oEtO+OmaP7vjXqmHvFtVVIO4WDIDZzwVSHscn/l4l9WZW74KAoz5RBZtXsEujTfn9Zo+sufrUoatLBBIh+M/CncYy+q1d2Dfjec7XJTxgjDo5zzYqRk+dkdOMfsat97fBBrqJcnEne6qEyqLzy5RKmOWh6mtyeaDD+uLbtUb1ldKjtJTXvfd0YK0nH4IyFkTfpB8RIDqSxVN+IMbLv+2xi4JVIc2Ax2FjIHE0Eva30mPfVByEB67U5MWWimoaIpbdeNcpEKDzLWr6GTze05fyNK2BwwQBgUjl5TbFTvUs4iL39jzwhEInPVvAHE1HrNlr8c=
  gem: url_tracking_api_client
  on:
    tags: true
    branch: master
    repo: TINYhr/url_tracking_api_client
